### ISSUE TITLE
Wrong temperature 

### ISSUE THREAD

**Issue by Niksunen** [thekroko/em3evbms#2]
App show wrong temperature. Old "original" app show temp right. I think this app show bms fet temp or something similar. It is always too warm. So it is not show actual cells temp like original old app.  Example i take my battery outside of my house for half hour, and in old app temp was +16.2c and this app show still +29c. And when battery is outside like 12h below zero temperature, your app show +26 and old app show almost zero. 

So i in this state you only monitor some other temp sensor than that one which is located to cells. Example many bt bms has actual Fet / Mos temp, Balance temp and one or more actual cell temps.  And fet/mos or balance is always much higher than cells.

There is picture of old app when battery has been outside of my house for 30 min (at -2c temp)
![IMG_20221024_105135](https://user-images.githubusercontent.com/20700028/197475590-d8f6f480-dd4c-4a45-8cb7-b44b5a62b1a5.jpg)

and there is screenshot for your app at same time as picture above. See big difference in temp readings. 
![IMG_20221024_105255](https://user-images.githubusercontent.com/20700028/197475842-c2e7c33e-8318-4aae-82be-4ede3ddedeb5.jpg)

**Comment by thekroko** [comment]
Current temperature parsing code is [here](https://github.com/thekroko/em3evbms/blob/main/BmsMonitor/app/src/main/java/com/kroko/bmsmonitor/Em3evBms.kt#L183). Effectively it reads the two bytes (e.g. 0x0B 0x86), turns them into an ushort (2950), and divides it by 100 (29.5).

I took a closer look at your recorded differences (very helpful!), and it looks like the value is actually recorded in 0.1 increments in Kelvin, i.e.
* (29.5c wrong) 2950 --> 295.0 kelvin --> 21.8c
* (27.3c wrong) 2730 --> 273.0 kelvin --> -0.1c

**Comment by thekroko** [comment]
I published a new version today that should fix this. Let me know if that isn't the case
